modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/SolidBlock-cn/reasonable-sorting/issues"
license = "LGPL-3.0"

[[mods]]
modId = "reasonable_sorting"
version = "${version}"
displayName = "Reasonable Sorting"
authors = "SolidBlock"
description = '''
Sorts blocks and items in the creative inventory reasonably.
'''
#logoFile = ""

[[dependencies.reasonable_sorting]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reasonable_sorting]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reasonable_sorting]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.0.0,)"
ordering = "NONE"
side = "BOTH"