modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/SolidBlock-cn/reasonable-sorting/issues"
license = "LGPLv3"

[[mods]]
modId = "reasonable-sorting"
version = "${version}"
displayName = "Reasonable Sorting"
authors = "SolidBlock"
description = '''
Sorts blocks and items in the creative inventory reasonably.
'''
#logoFile = ""

[[dependencies.reasonable-sorting]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reasonable-sorting]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.18.2)"
ordering = "NONE"
side = "BOTH"